### PR TITLE
Renamed sample -> samplePos because sample is a keyword in future glsl versions

### PR DESCRIPTION
**Pull request by NicholasBlaskey**
This isn't a big deal or perhaps something not worth while at all

but some version in glsl ```sample``` got turned into a keyword (for me it didn't work on 4.1 core) causing a shader compilation error in the ssao example.

[This spec shows it on page 25](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.50.pdf).

My one argument for it is that up until this point everything has worked great (love the tutorial so much btw) on 4.1 core but I totally understand not wanting to worry about future versions.

### CODE REVIEW

**Comment by JoeyDeVries** [comment]
Thanks @NicholasBlaskey ! Since it was only the SSAO chapter it didn't seem like it'll hurt too much to update this for future versions, I've updated the online SSAO text as well :)
