### ISSUE TITLE
how did you get freetype.lib in lib folder

### ISSUE THREAD

**Issue by zinwalin** [JoeyDeVries/LearnOpenGL#196]
freetype issue ld: symbol(s) not found for architecture x86_64

![image](https://user-images.githubusercontent.com/5416196/93014713-e6664780-f5e5-11ea-81fe-968abd634189.png)

compile on macOS 10.15.6

**Comment by rbarkmore** [comment]
Freetype.lib in the lib folder is a 64 bit library compiled in Windows, and should only be used in Windows.  For Linux, one would use 'sudo apt-get' to download and install the Freetype shared object.  I haven't used macOS and have no way to test with macOS, but the equivalent action as 'sudo apt-get' should allow you to download and install Freetype.

The CMakeLists.txt in the root directory has been updated with Freetype for Windows and for Linux.  If you get things working on macOS and you feel comfortable, please update CMakeLists.txt with the proper steps to install Freetype.  

Thanks.

**Comment by rbarkmore** [comment]
In the Readme.md, the section for Mac OS X building has this sequence:

`brew install cmake assimp glm glfw`

If you try `brew install freetype`, what happens?  (It may need freetype2, just a guess.)

Please let us know what happens.  Thanks.

**Comment by zinwalin** [comment]
> In the Readme.md, the section for Mac OS X building has this sequence:
> 
> `brew install cmake assimp glm glfw`
> 
> If you try `brew install freetype`, what happens? (It may need freetype2, just a guess.)
> 
> Please let us know what happens. Thanks.

![Uploading image.png…]()
