### ISSUE TITLE
Does not build on FreeBSD 13.2-RELEASE

### ISSUE THREAD

**Issue by Atticus-X** [JoeyDeVries/LearnOpenGL#361]
FreeBSD system information:
uname -a
FreeBSD *** 13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC amd64

The cmake file produces the following error when building:
LearnOpenGL-master/includes/GLFW/glfw3.h:162:14: fatal error: 'GL/gl.h' file not found #include <GL/gl.h>

Here-'s an edited cmake file that compiles and builds onFreeBSD.

Atticus

[CMakeLists.txt](https://github.com/JoeyDeVries/LearnOpenGL/files/11793906/CMakeLists.txt)
